/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufmt.ic.alg3.cinema.telas;

import br.ufmt.ic.alg3.cinema.entidades.Assento;
import br.ufmt.ic.alg3.cinema.entidades.Ingresso;
import br.ufmt.ic.alg3.cinema.entidades.Sessao;
import br.ufmt.ic.alg3.cinema.persistencia.AssentoDAO;
import br.ufmt.ic.alg3.cinema.persistencia.IngressoDAO;
import br.ufmt.ic.alg3.cinema.persistencia.SessaoDAO;
import br.ufmt.ic.alg3.cinema.utils.DAOFactory;
import java.math.BigDecimal;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author henrique
 */
public class JPanelIngresso extends javax.swing.JPanel {

    private IngressoDAO ingressoDAO = DAOFactory.createIngressoDAO();
    private AssentoDAO assentoDAO = DAOFactory.createAssentoDAO();
    private SessaoDAO sessaoDAO = DAOFactory.createSessaoDAO();
    
    /**
     * Creates new form JPanelIngresso
     */
    public JPanelIngresso() {
        initComponents();
        carregarTabela();
    }

    private void carregarTabela() {
        List<Ingresso> ingressos = ingressoDAO.listar();
        
        DefaultTableModel tableModel = (DefaultTableModel) jTableIngresso.getModel();
        
        // Limpar a tabela
        int linhas = tableModel.getRowCount();
        for (int i = 0; i < linhas; i++) {
            tableModel.removeRow(0);
        }
        
        // Preencher a tabela
        for (Ingresso ingresso : ingressos) {
            Object[] linha = new Object[6];

            linha[0] = ingresso.getId();
            linha[1] = ingresso.getSessao().getId();
            linha[2] = "R$ " + ingresso.getValor();
            linha[3] = ingresso.getMeia() ? "Meia" : "Inteira";
            linha[4] = ingresso.getAssento().getNumero();
            linha[5] = ingresso.getAssento().getSala().getNome();
            
            tableModel.addRow(linha);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupTipo = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldId = new javax.swing.JTextField();
        jTextFieldSessao = new javax.swing.JTextField();
        jTextFieldValor = new javax.swing.JTextField();
        jTextFieldAssento = new javax.swing.JTextField();
        jRadioButtonInteira = new javax.swing.JRadioButton();
        jRadioButtonMeia = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableIngresso = new javax.swing.JTable();
        jButtonSalvar = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();

        jLabel1.setText("ID:");

        jLabel2.setText("Sessão:");

        jLabel3.setText("Valor:");

        jLabel4.setText("Tipo:");

        jLabel5.setText("Assento:");

        jTextFieldId.setEditable(false);
        jTextFieldId.setEnabled(false);

        jTextFieldValor.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        buttonGroupTipo.add(jRadioButtonInteira);
        jRadioButtonInteira.setSelected(true);
        jRadioButtonInteira.setText("Inteira");

        buttonGroupTipo.add(jRadioButtonMeia);
        jRadioButtonMeia.setText("Meia");

        jTableIngresso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Sessão", "Valor", "Tipo", "Assento", "Sala"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableIngresso.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableIngresso);

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonLimpar.setText("Limpar");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        jButtonEditar.setText("Editar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldSessao, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldAssento, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadioButtonInteira)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jRadioButtonMeia))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonSalvar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonLimpar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonEditar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonExcluir)))
                        .addGap(0, 102, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldSessao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jRadioButtonInteira)
                    .addComponent(jRadioButtonMeia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldAssento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalvar)
                    .addComponent(jButtonLimpar)
                    .addComponent(jButtonEditar)
                    .addComponent(jButtonExcluir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        jTextFieldId.setText("");
        jTextFieldSessao.setText("");
        jTextFieldValor.setText("");
        jRadioButtonInteira.setSelected(true);
        jTextFieldAssento.setText("");
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        Ingresso novoIngresso = new Ingresso();
        
        int id = 0;
        try {
            id = Integer.parseInt(jTextFieldId.getText());
        } catch (NumberFormatException ex) {
            id = 0;
        }
        
        novoIngresso.setId(id);

        int idSessao = Integer.parseInt(jTextFieldSessao.getText());
        Sessao sessao = sessaoDAO.getById(idSessao);
        novoIngresso.setSessao(sessao);
        
        BigDecimal valor = new BigDecimal(jTextFieldValor.getText());
        novoIngresso.setValor(valor);
        
        if (jRadioButtonInteira.isSelected()) {
            novoIngresso.setMeia(false);
        } else {
            novoIngresso.setMeia(true);
        }
        
        int idAssento = Integer.parseInt(jTextFieldAssento.getText());
        Assento assento = assentoDAO.getById(idAssento);
        
        // Só é possível cadastrar um Ingresso caso seu Assento esteja vago
        if (assento == null) {
          JOptionPane.showMessageDialog(this, "O assento informado não existe", "Erro", JOptionPane.ERROR_MESSAGE);
        } else if (assentoDAO.getAssentoOcupado(idAssento)) {
            JOptionPane.showMessageDialog(this, "Assento já reservado", "Erro", JOptionPane.ERROR_MESSAGE);
        } else if (assento.getSala().getId() != sessao.getSala().getId()) {
            JOptionPane.showMessageDialog(this, "O assento informado não pertence à sala da sessão", "Erro", JOptionPane.ERROR_MESSAGE);
        } else {
            novoIngresso.setAssento(assento);

            if (ingressoDAO.getById(id) == null) {
                ingressoDAO.inserir(novoIngresso);
            } else {
                ingressoDAO.editar(novoIngresso);
            }
            
            jButtonLimparActionPerformed(evt);
            carregarTabela();
        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        int linha = jTableIngresso.getSelectedRow();
        
        if (linha != -1) {
            int id = (int) jTableIngresso.getValueAt(linha, 0);
            
            Ingresso ingresso = ingressoDAO.getById(id);
            
            jTextFieldId.setText(Integer.toString(ingresso.getId()));
            
            jTextFieldSessao.setText(Integer.toString(ingresso.getSessao().getId()));
            
            jTextFieldValor.setText(ingresso.getValor().toString());
            
            if (ingresso.getMeia()) {
                jRadioButtonMeia.setSelected(true);
            } else {
                jRadioButtonInteira.setSelected(true);
            }
            
            jTextFieldAssento.setText(Integer.toString(ingresso.getAssento().getId()));
        }
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        int[] linhas = jTableIngresso.getSelectedRows();
        
        for (int linha : linhas) {
            int id = (int) jTableIngresso.getValueAt(linha, 0);
            
            ingressoDAO.remover(id);
        }
        
        carregarTabela();
    }//GEN-LAST:event_jButtonExcluirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupTipo;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton jRadioButtonInteira;
    private javax.swing.JRadioButton jRadioButtonMeia;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableIngresso;
    private javax.swing.JTextField jTextFieldAssento;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldSessao;
    private javax.swing.JTextField jTextFieldValor;
    // End of variables declaration//GEN-END:variables
}
